#!/bin/bash

list=$1
N=`wc ${1} | awk '{print $1}'`
threads=96
#threadsX2=$((${threads}*2))

ABCD=/scratch/03263/jcha9928/data/ABCD/
ABCD_code=$ABCD/code_abcd
ABCD_job=$ABCD_code/job
#DATA_target=$STERN/image03/dwi_eddy

CMD_batch=$ABCD_code/cmd.ABCD.batch.fs.${list}
rm -rf $CMD_batch


i=1
for s in `cat $ABCD_code/$list`
do
#s=`echo $SUBJECT | egrep -o '[0-9]{8}'`
T1name=`echo $s | cut -d"." -f1`
SUBJECT=`echo $T1name | cut -d"_" -f1`
DATA_source=$ABCD/data/${s}
DATA_target=$ABCD/fs


  CMD=$ABCD_job/fs.stampede2.${T1name}
  rm -rf $CMD


cat<<EOC >$CMD
#!/bin/bash
source ~/.bashrc

tar -xzvf $ABCD/data_T1_release2_201905/${s} -C /tmp

T1w=\`find /tmp/*$SUBJECT -name "*_T1w.nii" | head -n 1\`

rm -rf /tmp/${SUBJECT}/

################################################################################
################################## freesurfer ##################################
################################################################################

sleep $[ ( $RANDOM % 10 )  + 1 ]s

recon-all -sd /tmp \
          -all \
          -s ${T1name} \
          -i \${T1w} \
          -qcache

################################################################################
################################################################################
################################################################################


echo "I THINK EVERYTHING IS DONE BY NOW"

cp -frv /tmp/${T1name} ${DATA_target}

EOC

################################################## END OF CMD###################
chmod +x $CMD
echo "$CMD > ./job/fs_output_subject_${T1name}_\${LAUNCHER_JID}_\${LAUNCHER_TSK_ID} 2>&1 " >> $CMD_batch

done

### batch submission############################################################

split -l $n_split $CMD_batch batch_fs_

cat<<EOM > ${ABCD_job}/launcher_script
#!/bin/bash
#SBATCH -J abcd_fs         # Job name
#%###SBATCH -o ./job/ABCD_a2.o%j       # Name of stdout output file
#%###SBATCH -e ./job/ABCD_a2.e%j       # Name of stderr error file
#SBATCH -p skx-normal          # Queue (partition) name
#SBATCH -N 31                            # Total # of nodes
#SBATCH --ntasks-per-node 48            # Total # of mpi tasks
#SBATCH -t 48:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=cha.jiook@gmail.com
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A TG-IBN180001

module list
pwd
date
module load launcher
sleep 3

export LAUNCHER_PLUGIN_DIR=\$LAUNCHER_DIR/plugins
export LAUNCHER_RMI=SLURM
export LAUNCHER_JOB_FILE=`echo $job_script`

# Launch MPI code...
\$LAUNCHER_DIR/paramrun


EOM

echo sbatch $launch_script
